### PR TITLE
Added logic to load locations and VM sku's from json files

### PR DESCRIPTION
**Pull request by fireblade95402**
## PR Summary

This change loads the vm sku's from a json file by location that is generated by a bash script in the build.yml action. Plus, loads the locations from another locations.json file.

The genertation of toe sku's is driven from a locations.json and skuFamilies.json files, which needs to be manually updated at this point in time. 

The current locations and skufamilies files are aligned to the current list from main, excluding UKSouth2, which wasn't found in the API calls to fetch the sku's.

The screen has changed to also a custom sku to be entered and sku name has been added to the dropdown

Logic has also been added to handle the 3 compute types on the screen, but the IO Optimized and GPU Workloads are disabled for now.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] This PR is ready to merge and is not **Work in Progress**
- [x] Link to a filed issue
- [x] Screenshot of UI changes (if PR includes UI changes)
image

### CODE REVIEW

**Comment by fireblade95402** [comment]
@Gordonby I made an attemp to add the bash script to the build.yml process. I wasn't sure if if was correct or not. Plus, not too sure how to test it.

**Comment by Gordonby** [comment]
This looks really good @fireblade95402 
Let me spin it up in a codespace

**Comment by Gordonby** [comment]
## befpre

image

## after

image

**Comment by Gordonby** [comment]
@fireblade95402  - i'm seeing this problem when running the script

image

**Comment by fireblade95402** [comment]
@Gordonby If I run the script with "./generate-vm-sku-list-v2.sh" it works and when I run it with "sh generate-vm-sku-list-v2.sh" I get the same error you get. I'll have a look at why

**Comment by fireblade95402** [comment]
Ok, I'm using "bash" shell and not the "sh" shell. Gather differences in language support. Should we be making it "sh" or would "bash" be ok

**Comment by Gordonby** [comment]
Needed to add an Azure Login step to the build, but now it works fine :)

image

**Review by Gordonby — APPROVED** [review]
lgtm.

we may want to revisit the script file to look for potential optimisation... But since it's just called once in release rather than by the UI - i think we're good.

**Pull request merged**
