### PR TITLE
Allow Helper URL parameters to set the defaults

### PR DESCRIPTION
**Pull request by khowling**
## PR Summary

Update browser URL parameters with the selected options from the helper, this allows bookmarking of preset configuration

However, this may be confusing to users, if they bookmark the site, and do not realise they are also saving there last config, instead of starting from the recommended presets. 

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [ ] This PR is ready to merge and is not **Work in Progress**
- [x] Link to a filed issue

### CODE REVIEW

**Comment by khowling** [comment]
@Gordonby this one is for you, but please build and run this locally before you approve, as I'm not sure I like the behaviour

**Comment by Gordonby** [comment]
Yes, I see what you mean.

Instead of changing the url as you navigate - could we have a "Bookmark this config" textbox somewhere?

**Comment by khowling** [comment]
@Gordonby , I've updated - see if you can spot the new field on the deploy tab

**Comment by Gordonby** [comment]
> @Gordonby , I've updated - see if you can spot the new field on the deploy tab

Oh lord.

image

**Comment by Gordonby** [comment]
what do you reckon @khowling ?

image

**Comment by khowling** [comment]
I really like your first one!

**Comment by Gordonby** [comment]
> I really like your first one!

Thats the one in the branch then 🛩️ 
Do you want to review the code is up to snuff, and we can get this one out there?

🚀

**Comment by Gordonby** [comment]
Do we need to add a Playwright test?
@khowling

**Review by Gordonby — APPROVED** [review]
quite a few tidying bits in here that i don't really get - but the app runs well, and the playwright tests pass

🚀

**Review by Gordonby — APPROVED** [review]
lgtm

**Pull request merged**
