### PR TITLE
Adding PowerShell Deployment Option to the Helper

### PR DESCRIPTION
**Pull request by fireblade95402**
## PR Summary

Added deployment option for PowerShell. Decided to to NOT change the az cli commands to PowerShell and only really change the postdeploy.sh script to postdeploy.ps1. I needed to change syntax in the helper and the release action to add in the new script, plus logic the handle old releases where the postdeplo.ps1 isn't available.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] This PR is ready to merge and is not **Work in Progress**
- [x] Link to a filed issue
- [x] Screenshot of UI changes (if PR includes UI changes)
image

### CODE REVIEW

**Comment by fireblade95402** [comment]
Need to check with the team on any functionality that might have been missed

**Comment by Gordonby** [comment]
The tab is disabled for me.
Is that expected?

image

**Comment by fireblade95402** [comment]
@Gordonby It has logic to disable the PowerShell tab if the postdeploy.ps1 isn't in the release. So need a release to test it out.

**Comment by Gordonby** [comment]
I'm getting an error when running this command

```pwsh
az deployment group create -g gordons  --template-file ./bicep/main.bicep --parameters `
resourceName=az-k8s-krcu `
SystemPoolType=Standard `
availabilityZones='["1","2\",\"3"]'
```

```output
InvalidAvailabilityZoneFormat

The specified Availability Zones [1 2\\\",\\\"3] are invalid and should be in numeric format.
```

image

**Review by Gordonby — APPROVED** [review]
lgtm

**Pull request merged**
