### PR TITLE
Adding NSG's for custom vnet

### LINKED ISSUE #244: NSG's, network flow logs and traffic analytics
When AKS-C deploys custom networking (a virtual network and subnets), I'd like it to be able to create
- Network Security Groups to limit the traffic appropriately for all subnets. (ie, For Bastion or Application Gateway only open the required ports)
- Network Flow Logs
- Traffic Analytics for the flow logs to easily spot when traffic is being dropped.

### LINKED ISSUE #245: Add GitHub reusable workflow to help failed deployment analysis
AKS deployments can fail for a variety of reasons.

Having a clear troubleshooting job (or number of jobs) at the end of a deployment would save time;
1. Gathering the data from the various sources
2. Initial analysis of these failures.

### LINKED ISSUE #259: Bump bicep to latest K8S version
We align the bicep k8s default to that of the Azure Portal default.

The most recent version is now 1.22.6
image

### PR DESCRIPTION
**Pull request by Gordonby**
## PR Summary

Adding in additional nsg definitions for when AKSC is deploying a custom virtual network.

This was done by deleting the specific AppGwNsg file and creating a single more parameter driven file that can deploy an NSG. EG. Both an Application Gateway subnet and a [Bastion subnet ](https://docs.microsoft.com/en-us/azure/bastion/bastion-nsg)that have very specific rules that are checked on association with a subnet.

Closes #244 - NSG's for all subnets
Closes #245 - CI/CD Troubleshooting workflow
Closes #259 - Kubernetes version default

## TODO
- [x] Deny SSH inbound the AKS nodepools
- [x] Fix troubleshooting workflow to work with AKS run cmd AND regular

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] This PR is ready to merge and is not **Work in Progress**
- [x] Link to a filed issue

### CODE REVIEW

**Comment by Gordonby** [comment]
As discussed, pulled the enablePrivateClusterPublicFQDN param from this branch

**Comment by Gordonby** [comment]
Tested on a standard AKS
image

**Comment by Gordonby** [comment]
Added UI for the 2 params
image

**Comment by Gordonby** [comment]
Ok - this looks good.

image

**Review by khowling — APPROVED** [review]
excellent addition!

**Pull request merged**
