### PR TITLE
upping the lychee-action GitHub Action version number

### PR DESCRIPTION
**Pull request by oliverlabs**
upping the lychee-action version number

## PR Checklist

- [ ] PR has a meaningful title
- [ ] Summarized changes
- [ ] This PR is ready to merge and is not **Work in Progress**
- [ ] Link to a filed issue
- [ ] Screenshot of UI changes (if PR includes UI changes)

### CODE REVIEW

**Comment by Gordonby** [comment]
Can you give some context around why @oliverlabs ?
Does it solve a problem?
Is this version stable, have you tested?

**Comment by pjlewisuk** [comment]
Specifically, we were seeing the broken link checker failing on https://shell.azure.com, it looks like this is because that UTL redirects to a login page which the link checker sees as a failure. In added `shell.azure.com` to an ignore list to prevent the error.

**Comment by oliverlabs** [comment]
no updates? @pjlewisuk can you approve?

**Review by pjlewisuk — APPROVED** [review]
Approved

**Pull request merged**
