### PR TITLE
Microsoft Defender for Containers

### LINKED ISSUE #119: Enable Defender profile on most secure cluster
**Is your feature request related to a problem? Please describe.**
Enable Defender profile on most secure cluster, covering AKS, ACR and AKV

**Describe the solution you'd like**
Add following option in AKS resource template , and a UI checkbox, defaulted to true on most secure cluster
```
    "securityProfile": {
                      "azureDefender": {
                        "enabled": true,
                        "logAnalyticsWorkspaceResourceId": "[parameters('workspaceResourceId')]"
                      }
                    }
```
ref: https://docs.microsoft.com/en-us/azure/defender-for-cloud/defender-for-containers-enable?tabs=aks-deploy-arm%2Ck8s-deploy-asc%2Ck8s-verify-asc%2Ck8s-remove-arc%2Caks-removeprofile-api&pivots=defender-for-container-aks#deploy-the-defender-profile

### PR DESCRIPTION
**Pull request by Gordonby**
## PR Summary

Closes #119 
Enables **Microsoft Defender for Containers** cluster enrolment

## UI Changes

image
image

## Preview

NB: This is a preview feature
image

> AzureDefender installation is not allowed since feature 'Microsoft.ContainerService/AKS-AzureDefender' is not enabled. Please see https://aka.ms/aks/previews for how to enable features.

## Result

After creating the cluster with Defender turned on, you can initiate a test which works great on the created cluster
image

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] This PR is ready to merge and is not **Work in Progress**
- [x] Link to a filed issue

### CODE REVIEW

**Comment by Gordonby** [comment]
Need to talk about this one on our next review @khowling 

Although the dependency is fine, enabling the defender feature is causing
> Dependency: Microsoft.OperationalInsights/workspaces; OrginalError: autorest/azure: Service returned an error. Status=404 Code=\\"ResourceNotFound\\" Message=\\"The Resource \'Microsoft.OperationalInsights/workspaces/log-byo\' under resource group \'innerloop\' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix\\"; AKSTeam: RP, Retriable: false. For more details about how to create and use log analytics workspace,  please refer to: https://aka.ms/new-log-analytics

**Comment by Gordonby** [comment]
Going to close this one whilst there's a few kinks.

**Comment by Gordonby** [comment]
Am reopening this as;
> Microsoft Defender for Containers has finally launched

**Comment by Gordonby** [comment]
The what-if looks a lot better than when I last ran this bicep code.

image

**Comment by Gordonby** [comment]
This feature seems a little flaky
The Az Aks Show command does not show the cluster to be enabled for "Azure Defender for Containers"...
image

However checking Microsoft Defender for Cloud shows that the cluster is configured.
image

**Comment by Gordonby** [comment]
Raised the issue in the AKS repo.
https://github.com/Azure/AKS/issues/2740

**Comment by Gordonby** [comment]
Have feature flagged Defender....  

🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀

**Comment by Gordonby** [comment]
Have feature flagged Defender....  

🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀

**Review by khowling — APPROVED** [review]
The big one has landed!

**Pull request merged**
