### PR TITLE
Added Cost Estimate Workflow job

### LINKED ISSUE #469: Cost Estimates
`Suggestion from StreamingClouds community`

Add cost estimation to the helper so as you configure the environment you see the costs.

> NB: I believe there is a Hackathon project that takes an arm template and estimates the cost. Perhaps we can leverage that.

### PR DESCRIPTION
**Pull request by Gordonby**
## PR Summary

Adds a new job to the workflow that estimates the monthly cost of the deployment, which is then saved as a workflow artifact.

> The purpose is to showcase additional features that can be integrated into Customers CI/CD pipelines, this does not affect the bicep/helper in any way.

image

Closes #469 

### BYO workflow
- Added cost prediction for environment. Ref #469 
- Bumped versions of dependant actions

#### Json output from the Estimate workflow step;
image

### Private cluster workflow
- Added cost prediction for environment. Ref #469 

### OSS Workflow
Additionally it solves the "OSS workflow, Get Latest AKSC release" item in #454 (Get latest AKSC version)

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] This PR is ready to merge and is not **Work in Progress**
- [x] Link to a filed issue

### CODE REVIEW

**Comment by Gordonby** [comment]
Once this issue gets fixed, i think we're good to merge this PR.

https://github.com/TheCloudTheory/arm-estimator/issues/149

**Comment by Gordonby** [comment]
> Once this issue gets fixed, i think we're good to merge this PR.
> 
> [TheCloudTheory/arm-estimator#149](https://github.com/TheCloudTheory/arm-estimator/issues/149)

Ready!

**Comment by Gordonby** [comment]
Thanks for the feedback @samaea 
I've set the workflow to not run Cost Estimate on PR.

image

**Comment by samaea** [comment]
Lgtm 👍

**Review by samaea — APPROVED** [review]
Lgtm 👍

**Pull request merged**
