### PR TITLE
CNI improvements and UI tweaks

### LINKED ISSUE #224: CNI v2 optimisations
Dynamic IP allocation and a pod subnet are part of https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni#frequently-asked-questions

We should increase the pod per node value for clusters that are using Dynamic IP allocation, and adjust the networking to propose a pod subnet.

### LINKED ISSUE #348: CI/CD samples - Add step to scale the cluster
As @khowling has spotted, so configuration issues don't come to light until you try to scale the cluster nodepools.

For the AKS Byo Vnet cluster, we should add this step
1. Scale the nodepools
2. Check that they scaled out successfully

### LINKED ISSUE #384: The preview feature warning is too subtle
`Feedback from Cloud Native Hack Hours`

It can be easy to miss the Preview feature warning when using features like KEDA.

The result is a failed deployment because the subscriptions have not signed up to the previews.

### LINKED ISSUE #403: CNI Overlay
https://docs.microsoft.com/en-us/azure/aks/azure-cni-overlay

### LINKED ISSUE #408: GitHub Action Workflow deployment, tag
We should use the tag instead of main for the workflow

image

### LINKED ISSUE #409: Helper - Save Config
Promote the "Bookmark Config" to a button with a save icon further up the page.

image

### LINKED ISSUE #411: Enabling KEDA fails as it's behind a preview flag
**Describe the bug**
Enabling KEDA fails as it's behind a preview flag

**To Reproduce**
1. Go to Addon Details
2. Enable "KEDA : Enable Kubernetes Event-driven Autoscaling (KEDA) on the AKS Cluster"

`{
    "status": "Failed",
    "error": {
        "code": "BadRequest",
        "message": "Feature Microsoft.ContainerService/AKS-KedaPreview is not enabled. Please see https://aka.ms/aks/previews for how to enable features."
    }
}`

**Expected behavior**
Setup the Preview flag OR warn the user that it needs to enable the preview flag for KEDA : https://docs.microsoft.com/en-us/azure/aks/keda-deploy-add-on-arm#register-the-aks-kedapreview-feature-flag

az feature register --name AKS-KedaPreview --namespace Microsoft.ContainerService
**Screenshots**
image

### LINKED ISSUE #414: Allow Max Pods per node to be configured
Currently you can only configure pods per node in the bicep directly, the Helper does not expose the parameter.

### PR DESCRIPTION
**Pull request by Gordonby**
### CNI

Closes #403 - CNI Overlay networking
Closes #224 - Dynamic Ip addressing
Closes #414 - Max pods per node

#### UI

image
#### TODO

- [x] Add docs links to the UI
- [x] On selecting Dynamic IP Allocation, force the maxPods to go to 250
- [x] On selecting Overlay, override the size of the subnets
- [x] Test Overlay feature deploy
- [x] Test DIPA feature deploy
- [x] Test both features together
- [x] Test if overlay works with default networking
- [x] Add this #348

### Preview warning

Enhanced the preview warning, closes #384
image

#### Keda preview

Added link to Keda preview, closes #411
image

### Other

Also closes #409 by updating the querystring in the window as the user configures
Closes #348 - (Autoscale the cluster as part of CI/CD tests)
Closes #408 - (HelperUI GitHub action workflow using main instead of release tag)

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] This PR is ready to merge and is not **Work in Progress**
- [x] Link to a filed issue
- [x] Screenshot of UI changes (if PR includes UI changes)

### CODE REVIEW

**Comment by Gordonby** [comment]
Created #421 as i can't deal with the full UX on preview features in this PR. 😄

**Comment by Gordonby** [comment]
@Berniewhite - Any idea why PSRule says this?

> Error: Failed to expand parameter file '/home/runner/work/AKS-Construction/AKS-Construction/.github/workflows_dep/AksDeploy-ByoVnet.parameters.json'. Exception calling "GetResources" with "2" argument(s): "Bicep (0.10.61) compilation of '/home/runner/work/AKS-Construction/AKS-Construction/bicep/main.bicep' failed with: Bicep compilation hasn't completed within the timeout window. This can be caused by errors or warnings. Check the Bicep output by running bicep build and addressing any issues."

 -> .github/workflows_dep/AksDeploy-ByoVnet.parameters.json : .json [4/4]

https://github.com/Azure/AKS-Construction/actions/runs/3198569850/jobs/5223259003#step:3:70

The bicep builds fine in our deploy stage.

**Comment by BernieWhite** [comment]
@Gordonby PSRule has a limit it allows Bicep Build to run. By default this sis 5 seconds per .bicep file.

See https://azure.github.io/PSRule.Rules.Azure/troubleshooting/#bicep-compilation-timeout

**Comment by Gordonby** [comment]
> @Gordonby PSRule has a limit it allows Bicep Build to run. By default this is 5 seconds per .bicep file.
> 
> See https://azure.github.io/PSRule.Rules.Azure/troubleshooting/#bicep-compilation-timeout

Great thanks.

It was working for a long time, then stopped...  Changing the timeout looks like it's done the job.

**Review by khowling — APPROVED** [review]
bon voyage

**Pull request merged**
