### PR TITLE
Fix error when passing empty deploy.apiips on URL

### PR DESCRIPTION
**Pull request by khowling**
## PR Summary

Fix error when passing empty deploy.apiips on URL

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] This PR is ready to merge and is not **Work in Progress**
- [ ] Link to a filed issue

### CODE REVIEW

**Comment by khowling** [comment]
closes #301

**Comment by Gordonby** [comment]
Testing with this querystring looks great

```text
?ops=managed&secure=normal&deploy.apiips=&deploy.clusterAdminRole=true&deploy.clusterIPWhitelist=false&deploy.acrPushRole=false&deploy.kvCertSecretRole=false&cluster.apisecurity=none
```

**Comment by Gordonby** [comment]
I notice you've removed the eslint hint

```text
// eslint-disable-next-line react-hooks/exhaustive-deps
```

This was added initially to surpress the eslint warning
image

**Review by Gordonby — APPROVED** [review]
lgtm

**Comment by khowling** [comment]
> I notice you've removed the eslint hint
> 
> ```
> // eslint-disable-next-line react-hooks/exhaustive-deps
> ```
> 
> This was added initially to surpress the eslint warning image

Ah! good spot, I may put this back in!

**Pull request merged**
