### PR TITLE
Added Traefik as an available ingress controller

### PR DESCRIPTION
**Pull request by MattLeach25**
## PR Summary

Added Traefik as an available ingress controller to postdeploy script and options in the GUI.

Fixed a bug with NGINX where the helm chart would deploy, however there was no pods or services deployed. This turned out to be a typo within the postdeploy script.

This PR covers feature #96 

image

image

image

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] This PR is ready to merge and is not **Work in Progress**
- [x] Link to a filed issue
- [x] Screenshot of UI changes (if PR includes UI changes)

### CODE REVIEW

**Comment by Gordonby** [comment]
Looks good to me.

Just make sure to add traefik to the cspell dictionary ([cspell.json](https://github.com/Azure/AKS-Construction/blob/main/cspell.json))
image

@khowling - Can you take a look?

**Review by Gordonby — DISMISSED** [review]
LGTM - But i'll let Keith provide the final approval for merge.

**Comment by Gordonby** [comment]
@msftbot merge the PR once @khowling approves.

**Comment by khowling** [comment]
Hey Matt, looks great! thanks for catching the case bug for nginx,  just a couple of questions for qa.
1. ingress_controller_kind  - this is used by nginx and contour, and now traefik.  Does the change work with contour, or do we need to have a special logic for contour?  (I think I did most of my testing originally with contour & so bit worried it will break)
2. When adding a ingress controller, I like to test with the most complex options with certman / external-dns and grafana, to see if you get a ssl fqdn for grafana.  If that all works, then we are in good shape

**Comment by Gordonby** [comment]
@MattLeach25 I can walk you through these advanced testing scenarios on Monday. Stick some time in.

**Comment by MattLeach25** [comment]
> @MattLeach25 I can walk you through these advanced testing scenarios on Monday. Stick some time in.

Keith has already talked me through the changes so I can get going. If I get stuck I’ll pop up next week :)

thanks both.

**Comment by Gordonby** [comment]
Added tests to cover Traefik install

image

**Comment by Gordonby** [comment]
OK. I'm pretty confident we just need to enable the traefik version of this nginx feature @MattLeach25 

<html>
<body>


--publish-service | Service fronting the Ingress controller. Takes the form "namespace/name". When used together with update-status, the controller mirrors the address of this service's endpoints to the load-balancer status of all Ingress objects it satisfies.
-- | --



</body>
</html>

**Comment by Gordonby** [comment]
Damn. Maybe not.

image

Ok, lets find the problem next week!

**Comment by Gordonby** [comment]
Looks like this has fixed it @MattLeach25 

```
--set providers.kubernetesIngress.publishedService.enabled=true
```

---

````
helm upgrade --install traefik traefik/traefik \
        --set deployment.kind="Deployment" \
        --set service.spec.externalTrafficPolicy=Cluster \
        --set metrics.prometheus.enabled=true \
        --set providers.kubernetesIngress.publishedService.enabled=true \
        --set logs.general.level=INFO \
        --set logs.access.enabled=true \
        --set ports.traefik.expose=false \
        --set additionalArguments={--log.level=DEBUG} \
        --namespace ingress-basic 
```

**Review by Gordonby — APPROVED** [review]
LGTM

image

**Pull request merged**
