### PR TITLE
Alter default outbound Networking options #619

### PR DESCRIPTION
**Pull request by nellyk**
## PR Summary
Alter default outbound networking options as per #619 

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] This PR is ready to merge and is not **Work in Progress**
- [x] Link to a filed issue
- [x] Screenshot of UI changes (if PR includes UI changes)

### CODE REVIEW

**Comment by Gordonby** [comment]
The Playwright tests will need to be reverted to what they looked like a few months ago if we're reverting this default... That's why the build is failing.

**Comment by Gordonby** [comment]
@nellyk - I've reverted the Playwright test for you.
This should be ready to merge once one of the core team approves.

**Comment by pjlewisuk** [comment]
Tested the following configurations:

- **Non-Production:**
    - *Cluster with additional security controls* - defaults to SLB
    - *Private cluster with isolating network controls* - defaults to firewall (UDR)
- **Production:**
    - *Cluster with additional security controls* - defaults to SLB
    - *Private cluster with isolating network controls* - defaults to firewall (UDR)

All four configurations deployed correctly, and when I visually inspected the resource groups they had the correct resources for egress (load balancer vs firewall).

Had to revert to bicep 0.20.4 for testing due to #656 which has started happening since bicep 0.21.1.

**Review by pjlewisuk — APPROVED** [review]
Tested the following configurations:

- **Non-Production:**
    - *Cluster with additional security controls* - defaults to SLB
    - *Private cluster with isolating network controls* - defaults to firewall (UDR)
- **Production:**
    - *Cluster with additional security controls* - defaults to SLB
    - *Private cluster with isolating network controls* - defaults to firewall (UDR)

All four configurations deployed correctly, and when I visually inspected the resource groups they had the correct resources for egress (load balancer vs firewall).

Had to revert to bicep 0.20.4 for testing due to #656 which has started happening since bicep 0.21.1.

Happy for this to be merged.

**Pull request merged**
