### PR TITLE
Fixing Dapr + Flux race condition

### LINKED ISSUE #385: Deployment issue with Flux: Another operation is in progress
`Feedback from Cloud Native Hack Hours`

**Describe the bug**
Issue from deployment which appears to be due to another operation happening, but no other deployment was happening in the subscription.

**To Reproduce**

```
# az group create -l southCentralUS -n aks-lza-live-rg

Location        Name
--------------  ---------------
southcentralus  aks-lza-live-rg

# az deployment group create -g aks-lza-live-rg  --template-uri https://github.com/Azure/AKS-Construction/releases/download/0.8.9/main.json --parameters \
        resourceName=aks-lza-live \
        upgradeChannel=stable \
        agentCountMax=20 \
        custom_vnet=true \
        enable_aad=true \
        AksDisableLocalAccounts=true \
        enableAzureRBAC=true \
        adminPrincipalId=$(az ad signed-in-user show --query id --out tsv) \
        registries_sku=Premium \
        acrPushRolePrincipalId=$(az ad signed-in-user show --query id --out tsv) \
        omsagent=true \
        retentionInDays=30 \
        networkPolicy=azure \
        openServiceMeshAddon=true \
        azurepolicy=audit \
        ingressApplicationGateway=true \
        appGWcount=0 \
        appGWsku=Standard_v2 \
        appGWmaxCount=10 \
        appgwKVIntegration=true \
        keyVaultAksCSI=true \
        keyVaultCreate=true \
        keyVaultOfficerRolePrincipalId=$(az ad signed-in-user show --query id --out tsv) \
        fluxGitOpsAddon=true \
        daprAddon=true
```

Error after [14m11.2s]
```
{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. 
Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"ExtensionOperationFailed\",\r\n        
\"message\": \"The extension operation failed with the following error:  
Request failed to https://management.azure.com/subscriptions/df8428d4-bc25-4601-b458-1c8533ceec0b/resourceGroups/aks-lza-live-rg/providers/Microsoft.ContainerService/managedclusters/aks-aks-lza-live/extensionaddons/dapr?api-version=2021-03-01. Error code: Conflict. 
Reason: Conflict.{\\n  \\\"code\\\": \\\"EtagMismatch\\\",\\n  \\\"message\\\": \\\
"Operation is not allowed: Another operation is in progress\\\",\\n  \\\"subcode\\\": \\\
"PutManagedClusterAndAgentPools_FailedPrecondition\\\"\\n }.\"\r\n      }\r\n    ]\r\n  }\r\n}"}]}}                                                                                                                                                                                                        
```
**Expected behavior**
I expected a successful deployment.

**Additional context**

Discovered during the Cloud Native Hack Hours.

### LINKED ISSUE #389: Not specifying UpgradeChannel parameter leads to unpredictable behaviour
In the Helper, if you don't choose a parameter value for UpgradeChannel, the bicep uses an empty string. The default in the helper is 'none'.

image

image

However the bicep code parameter does not have a default of none(the default is empty string), and this leads to a deployed cluster having the value of `upspecified`
image
The behaviour results in the system pool being upgraded.

The bicep code parameter should have a default value of 'none', so the behaviour of the upgrades are more predictable.

### PR DESCRIPTION
**Pull request by Gordonby**
## PR Summary

This fixes a bug where if you configured Flux and Dapr, then they would conflict with each other whilst installing simultaneously.

It also addresses another small issue with the default parameter value for upgradeChannel

Closes #385 
Closes #389 

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] This PR is ready to merge and is not **Work in Progress**
- [x] Link to a filed issue

### CODE REVIEW

**Review by khowling — APPROVED** [review]
awesome fixes, good investigation!!

**Comment by joshuadmatthews** [comment]
I am having this issue even with the dependencies chained, I can see that flux is fully finished before dapr starts up yet, dapr is the only thing deploying while it is deploying, I yet still get the EtagMismatch error. Any ideas?

**Comment by Gordonby** [comment]
> I am having this issue even with the dependencies chained, I can see that flux is fully finished before dapr starts up yet, dapr is the only thing deploying while it is deploying, I yet still get the EtagMismatch error. Any ideas?

Can you share the full error?
Just redact your subscription Id etc.

**Comment by joshuadmatthews** [comment]
{
    "status": "Failed",
    "error": {
        "code": "ExtensionOperationFailed",
        "message": "The extension operation failed with the following error:  Request failed to https://management.azure.com/subscriptions/xyz/resourceGroups/abc/providers/Microsoft.ContainerService/managedclusters/aks/extensionaddons/dapr?api-version=2021-03-01. Error code: Conflict. Reason: Conflict.{\n  \"code\": \"EtagMismatch\",\n  \"message\": \"Failed to save managed aks in subscription xyz, resource abc. Operation is not allowed: Another operation is in progress\",\n  \"subcode\": \"PutManagedClusterAndAgentPools_FailedPrecondition\"\n }."
    }
}

**Comment by joshuadmatthews** [comment]
I think it may be something else wrong with my cluster, even if I disable remove the flux addon I still get this error.

**Comment by joshuadmatthews** [comment]
Deleting my cluster and letting it recreate resolved the issue.

**Pull request merged**
