### PR TITLE
UI: User pool scale value changes

### LINKED ISSUE #228: UI: Allow the user pool to scale from zero nodes
**Is your feature request related to a problem? Please describe.**
One of the benefits of seperate userpools is the ability to scale from zero nodes.

The UI currently limits the user pools to a minimum of 1.

The UI would need to dynamically set the minimum between 0 and 1 depending or whether or not there was a dedicated system pool being deployed.

### PR DESCRIPTION
**Pull request by Gordonby**
## PR Summary

This optimises the node scale values to allow;

- Minimum node to be 0 when `scale type is autoscale` and a `user pool` will be deployed in addition to the system pool.
- Max nodes to dynamically change it's min value based on the autoscaler minimum
- Max nodes step count to be 1 instead of 5.

Closes #228 

image

Strapped this up with Playwright tests to make check the correct behaviour of setting manual scale/no user pool
image

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] This PR is ready to merge and is not **Work in Progress**
- [x] Link to a filed issue

### CODE REVIEW

**Comment by Gordonby** [comment]
Added Playwright tests @khowling - can you review please?

**Comment by khowling** [comment]
@Gordonby , I've pushed the new slider logic in the helper, pls chck it out

**Comment by Gordonby** [comment]
> @Gordonby , I've pushed the new slider logic in the helper, pls chck it out

looks really good! 🚀 

image

**Comment by Gordonby** [comment]
Still have 1 playwright test to fix before we can sail this one through @khowling

**Pull request merged**
