### PR TITLE
Fix images on the tiles

### PR DESCRIPTION
**Pull request by AdityaAgarwaal**
## PR Summary

This PR solves the issue #624 

The images on the tiles present on the route https://azure.github.io/AKS-Construction/?preset=entScaleOps were not getting rendered.

image

After changing the imageFit prop in DocumentCardImage component from "centerCover" to  "cover" and adding a flex column between the image and the description title, the images were correctly rendered.

image

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] This PR is ready to merge and is not **Work in Progress**
- [x] Link to a filed issue
- [x] Screenshot of UI changes (if PR includes UI changes)

### CODE REVIEW

**Comment by AdityaAgarwaal** [comment]
> @microsoft-github-policy-service agree

**Comment by AdityaAgarwaal** [comment]
@microsoft-github-policy-service agree

**Review by khowling — CHANGES_REQUESTED** [review]
Thank you for your PR,  There are a lot of changes in the file, I think most of them are just whitespace/linebreak formatting changes. 

Images look good!!   but it looks like the changes have altered the formatting of the icon-based tiles too,  this is the current layout:
image

this is the layout for this branch: 

image

Could you take a look pls

**Comment by AdityaAgarwaal** [comment]
Thank you for your review, I have resolved the issue you mentioned in this commit, please review it.

This is the view of the card when the icon will be rendered

image

This is the view of when the image will be rendered

image

**Comment by AdityaAgarwaal** [comment]
@khowling please review the changes. Thankyou

**Comment by AdityaAgarwaal** [comment]
@khowling please review this PR. Thanks

**Review by pjlewisuk — CHANGES_REQUESTED** [review]
Hey @AdityaAgarwaal, thanks for the submission and the update. Unfortunately, when I load your branch up in a codespace and run the helper using `npm start`, I don't see the images at all:

image

Can you double-check that everything is working as expected when you run the helper?

**Comment by AdityaAgarwaal** [comment]
Yes, I will check and get back to you.

Thanks

**Pull request closed without merging**
